version: '3.8'

services:
  
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  # .NET 8 API
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0 AS base
    container_name: dotnet_api
    build:
      context: ./api # Path to your .NET API project
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=mydb;User=user;Password=userpassword;
    ports:
      - "5000:80" # Mapping .NET API to port 5000
    depends_on:
      - mysql
    networks:
      - mynetwork

  # React JS App
  reactapp:
    build:
      context: ./client # Path to your React JS project
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
