version: '3.8'

services:
  
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cafenetwork

  # .NET 8 API
  api:
    container_name: dotnet_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=mydb;User=user;Password=userpassword;
    ports:
      - "5000:8080"
    depends_on:
      - mysql
    networks:
      - cafenetwork

  # React JS App
  reactapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - cafenetwork

volumes:
  db_data:

networks:
  cafenetwork:
    driver: bridge
